apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "concourse-webhook.fullname" . }}
  labels:
    app: {{ template "concourse-webhook.name" . }}
    chart: {{ template "concourse-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "concourse-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "concourse-webhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagepullPolicy }}
          ports:
            - name: wh-cont-port
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
