resources:
- name: repo
  type: git
  source:
    branch: master
    uri: https://github.com/ministryofjustice/cloud-platform-tools-image

- name: image
  type: docker-image
  source:
    repository: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cloud-platform/tools
    aws_access_key_id: ((aws.access-key-id))
    aws_secret_access_key: ((aws.secret-access-key))

jobs:
  - name: build-tools-image
    serial: true
    plan:
      - aggregate:
        - get: repo
          trigger: true
        - get: image
      - task: ensure-repository-exists
        image: image
        config:
          platform: linux
          params:
            AWS_DEFAULT_REGION: eu-west-1
            AWS_ACCESS_KEY_ID: ((aws.access-key-id))
            AWS_SECRET_ACCESS_KEY: ((aws.secret-access-key))
          run:
            path: /bin/sh
            args:
              - -c
              - |
                aws ecr create-repository \
                  --repository-name cloud-platform/tools || echo "error ignored"
                aws ecr put-lifecycle-policy \
                  --repository-name cloud-platform/tools \
                  --lifecycle-policy-text '{
                    "rules": [
                      {
                        "rulePriority": 10,
                        "description": "remove-untagged",
                        "selection": {
                          "tagStatus": "untagged",
                          "countType": "sinceImagePushed",
                          "countUnit": "days",
                          "countNumber": 1
                        },
                        "action": {
                          "type": "expire"
                        }
                      }
                    ]}'
      - put: image
        params:
          build: repo
          tag_as_latest: true
          tag: repo/.git/ref
